/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.todo.application.UI;

import java.awt.Color;
import java.awt.Cursor;
import java.io.IOException;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Uomrod-PC
 */
public class SingleProject extends javax.swing.JPanel {
    private final Todo todoapp;
    private final Color myDeepBlack = new Color(50, 50, 50);
    private final Color myLightBlack = new Color(60, 60, 60);
    /**
     * Creates new form singleProject
     */
    public SingleProject(Todo mainUI) {
        initComponents();
        this.todoapp = mainUI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(50, 50, 50));
        setMinimumSize(new java.awt.Dimension(234, 50));
        setPreferredSize(new java.awt.Dimension(234, 50));

        jTextField1.setBackground(new java.awt.Color(60, 60, 60));
        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(227, 227, 227));
        jTextField1.setText("Project name");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 1));
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(227, 227, 227));
        jLabel1.setText("Save");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if (jLabel1.getText().equals("Save")) {
            jTextField1.setEditable(false);
            jTextField1.setBackground(myDeepBlack);
            jLabel1.setText("Edit");

//            if (this.isFirstEdit) {
//                try {
//                    this.docId = todoapp.getTaskController().addTask(todoapp.getUser().getEmail(), jTextField1.getText(), dateController.getDocFormat(this.date));
//                } catch (IOException | InterruptedException | ExecutionException ex) {
//                    Logger.getLogger(SingleTask.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                this.isFirstEdit = false;
//                
//            } else {
//                try {
//                    todoapp.getTaskController().updateTask(todoapp.getUser().getEmail(), this.docId, jTextField1.getText());
//                } catch (InterruptedException | ExecutionException ex) {
//                    Logger.getLogger(SingleTask.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//            todoapp.getjLabel9().setText("Database: save");
        } else {
            jTextField1.setEditable(true);
            jTextField1.setBackground(myLightBlack);
            jLabel1.setText("Save");
//            todoapp.getjLabel9().setText("Database:");
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel1MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
